// apps/example-apps/svelte/examples/misc/feature-overview/CircleNode.svelte
<script module>
  export type CircleNode = Node<{}>;
</script>

<script lang="ts">
  import { type NodeProps, Handle, type Node, Position } from '@xyflow/svelte';

  let { positionAbsoluteX, positionAbsoluteY }: NodeProps<CircleNode> =
    $props();

  let label = $derived(
    `position x:${Math.round(positionAbsoluteX)} y:${Math.round(positionAbsoluteY)}`,
  );
</script>

<div class="wrapper gradient">
  <div class="inner">{label || 'no node connected'}</div>
</div>
<Handle type="target" position={Position.Left} />

// sites/reactflow.dev/src/components/example-viewer/example-flows/Overview/CircleNode.jsx
import React, { memo } from 'react';
import { Handle, useStore, Position } from '@xyflow/react';

export default memo(({ id }) => {
  const label = useStore((s) => {
    const node = s.nodeLookup.get(id);

    if (!node) {
      return null;
    }

    return `position x:${parseInt(node.position.x)} y:${parseInt(
      node.position.y,
    )}`;
  });

  return (
    <>
      <div className="wrapper gradient">
        <div className="inner">{label || 'no node connected'}</div>
      </div>
      <Handle type="target" position={Position.Left} />
    </>
  );
});
