// apps/example-apps/svelte/examples/misc/feature-overview/ResizerNode.svelte
<script lang="ts">
  import {
    Handle,
    NodeResizer,
    Position,
    type NodeProps,
  } from '@xyflow/svelte';

  let { data }: NodeProps = $props();
</script>

<NodeResizer minWidth={100} minHeight={30} />
<Handle type="target" position={Position.Left} class="custom-handle" />
<div>{data.label}</div>
<div class="resizer-node__handles">
  <Handle
    class="resizer-node__handle custom-handle"
    id="a"
    type="source"
    position={Position.Bottom}
  />
  <Handle
    class="resizer-node__handle custom-handle"
    id="b"
    type="source"
    position={Position.Bottom}
  />
</div>

// sites/reactflow.dev/src/components/example-viewer/example-flows/Overview/ResizerNode.jsx
import { memo } from 'react';
import { Handle, Position, NodeResizer } from 'reactflow';

function ResizerNode({ data }) {
  return (
    <>
      <NodeResizer minWidth={50} minHeight={50} />
      <Handle type="target" position={Position.Left} />
      <div style={{ padding: 10 }}>{data.label}</div>
      <div
        style={{
          display: 'flex',
          position: 'absolute',
          bottom: 0,
          width: '100%',
          justifyContent: 'space-evenly',
          left: 0,
        }}
      >
        <Handle
          style={{ position: 'relative', left: 0, transform: 'none' }}
          id="a"
          type="source"
          position={Position.Bottom}
        />
        <Handle
          style={{ position: 'relative', left: 0, transform: 'none' }}
          id="b"
          type="source"
          position={Position.Bottom}
        />
      </div>
    </>
  );
}

export default memo(ResizerNode);
