// apps/example-apps/svelte/examples/misc/feature-overview/TextNode.svelte
<script lang="ts">
  import {
    type NodeProps,
    Handle,
    Position,
    useHandleConnections,
    useInternalNode,
    type BuiltInNode,
    type Dimensions
  } from '@xyflow/svelte';

  import { nodes } from './nodes-and-edges';

  type $$Props = NodeProps<BuiltInNode>;
  $$restProps;

  $: handleConnections = useHandleConnections({
    type: 'target'
  });

  $: connectedNode = useInternalNode($handleConnections[0]?.source);
  let dimensions: null | Dimensions = null;

  $: {
    if ($connectedNode?.measured.width && $connectedNode?.measured.height) {
      dimensions = {
        width: $connectedNode.measured.width,
        height: $connectedNode.measured.height
      };
    } else {
      dimensions = null;
    }
  }

  const updateDimension = (attr: string) => (event) => {
    nodes.update((nds) =>
      nds.map((n) => {
        if (n.id === '2-3') {
          return {
            ...n,
            [attr]: parseInt(event.target.value)
          };
        }

        return n;
      })
    );

    $nodes = $nodes;
  };
</script>

<div class="wrapper gradient">
  <div class="inner">
    {#each ['width', 'height'] as attr}
      <label>node {attr}</label>
      <input
        type="number"
        value={dimensions ? parseInt(dimensions[attr]) : 0}
        on:change={updateDimension(attr)}
        class="nodrag"
        disabled={!dimensions}
      />
    {/each}

    {#if dimensions === null}
      no node connected
    {/if}
  </div>
</div>
<Handle type="target" position={Position.Top} />

// sites/reactflow.dev/src/components/example-viewer/example-flows/Overview/TextNode.jsx
import React, { memo } from 'react';
import { Handle, useStore, Position, useReactFlow } from '@xyflow/react';

const dimensionAttrs = ['width', 'height'];

export default memo(({ id }) => {
  const { setNodes } = useReactFlow();
  const dimensions = useStore((s) => {
    const node = s.nodeLookup.get('2-3');

    if (
      !node ||
      !node.width ||
      !node.height ||
      !s.edges.some((edge) => edge.target === id)
    ) {
      return null;
    }

    return {
      width: node.width,
      height: node.height,
    };
  });

  const updateDimension = (attr) => (event) => {
    setNodes((nds) =>
      nds.map((n) => {
        if (n.id === '2-3') {
          return {
            ...n,
            style: {
              ...n.style,
              [attr]: parseInt(event.target.value),
            },
          };
        }

        return n;
      }),
    );
  };

  return (
    <>
      <div className="wrapper gradient">
        <div className="inner">
          {dimensionAttrs.map((attr) => (
            <>
              <label>node {attr}</label>
              <input
                type="number"
                value={dimensions ? parseInt(dimensions[attr]) : 0}
                onChange={updateDimension(attr)}
                className="nodrag"
                disabled={!dimensions}
              />
            </>
          ))}
          {!dimensionAttrs && 'no node connected'}
        </div>
      </div>
      <Handle type="target" position={Position.Top} />
    </>
  );
});
