// packages/xy-shared/widgets/hero-flow/color-picker-node.tsx
import { memo } from 'react';
import { NodeProps, Position, useReactFlow } from '@xyflow/react';
import { Text } from '@xyflow/xy-ui';

import Handle from './handle';
import Wrapper from './node-wrapper';

export default memo(({ data, id }: NodeProps) => {
  const { updateNodeData } = useReactFlow();

  return (
    <Wrapper label={data.label}>
      <div className="flex items-center space-x-2">
        <input
          className="nodrag border-md w-6 h-6"
          type="color"
          onChange={(evt) => updateNodeData(id, { value: evt.target.value })}
          defaultValue={data.value}
        />
        <Text size="xs" variant="light">
          {data.value}
        </Text>
      </div>
      <Handle type="source" position={Position.Right} />
    </Wrapper>
  );
});

// apps/example-apps/svelte/examples/misc/threlte-flow/ColorPickerNode.svelte
<script lang="ts">
  import { Handle, Position, type NodeProps, type Node } from '@xyflow/svelte';
  import NodeWrapper from './NodeWrapper.svelte';
  import { flowState, type NodeData } from './nodes-and-edges.svelte';

  let { data }: NodeProps<Node<NodeData>> = $props();
</script>

<NodeWrapper label={data.label}>
  <div class="flex items-center space-x-2 p-3">
    <input
      bind:value={flowState.color}
      class="nodrag border-md w-6 h-6"
      type="color"
    />
    <p>{flowState.color}</p>
  </div>
  <Handle type="source" position={Position.Right} />
</NodeWrapper>
