// packages/xy-shared/components/flows/hero-flow/slider-node.tsx
import { useCallback } from 'react';
import { Node, NodeProps, Position, useReactFlow } from '@xyflow/react';
import { Slider } from '../../../components/ui/slider';

import Handle from './handle';
import Wrapper from './node-wrapper';

const min = 0;
const max = 40;

export type SliderNode = Node<{ label: string; value: number }>;

export default function SliderNode({ data, id }: NodeProps<SliderNode>) {
  const { updateNodeData } = useReactFlow();
  const onValueChange = useCallback(
    (values: number[]) => updateNodeData(id, { value: values[0] }),
    [id, updateNodeData],
  );

  return (
    <Wrapper label={data.label}>
      <Slider
        className="nodrag m-2"
        min={min}
        max={max}
        value={[data.value]}
        onValueChange={onValueChange}
        inverted
        rangeClassName="bg-primary"
        thumbClassName="bg-primary"
      />
      <Handle type="source" position={Position.Right} />
    </Wrapper>
  );
}

// apps/example-apps/svelte/examples/misc/threlte-flow/SliderNode.svelte
<script lang="ts">
  import { Handle, type Node, Position, type NodeProps } from '@xyflow/svelte';
  import NodeWrapper from './NodeWrapper.svelte';
  import { flowState, type NodeData } from './nodes-and-edges.svelte';

  let { data }: NodeProps<Node<NodeData>> = $props();

  const min = 0;
  const max = 40;
</script>

<NodeWrapper label={data.label}>
  <Handle type="source" position={Position.Right} />
  <input
    class="nodrag accent-[#ff4000]"
    style="direction: rtl;"
    type="range"
    {min}
    {max}
    bind:value={flowState.zoom}
  />
</NodeWrapper>
