// packages/xy-shared/widgets/hero-flow/slider-node.tsx
import { Position } from '@xyflow/react';
import { Slider } from '@xyflow/xy-ui';

import Handle from './handle';
import Wrapper from './node-wrapper';

const min = 0;
const max = 40;

export default function SliderNode({ data }: { data: any }) {
  const { label = '', setState = () => {}, zoom = 12 } = data;

  return (
    <Wrapper label={label}>
      <Slider
        className="nodrag m-2"
        min={min}
        max={max}
        value={[zoom]}
        onValueChange={(val) =>
          setState((state: any) => ({ ...state, zoom: val[0] }))
        }
        inverted
        rangeClassName="bg-primary"
        thumbClassName="bg-primary"
      />
      <Handle type="source" position={Position.Right} />
    </Wrapper>
  );
}

// apps/example-apps/svelte/examples/misc/threlte-flow/SliderNode.svelte
<script lang="ts">
  import { Handle, type Node, Position, type NodeProps } from '@xyflow/svelte';
  import NodeWrapper from './NodeWrapper.svelte';
  import { flowState, type NodeData } from './nodes-and-edges.svelte';

  let { data }: NodeProps<Node<NodeData>> = $props();

  const min = 0;
  const max = 40;
</script>

<NodeWrapper label={data.label}>
  <Handle type="source" position={Position.Right} />
  <input
    class="nodrag accent-[#ff4000]"
    style="direction: rtl;"
    type="range"
    {min}
    {max}
    bind:value={flowState.zoom}
  />
</NodeWrapper>
