// apps/example-apps/svelte/learn/custom-edge-path/StepEdge.svelte
<script lang="ts">
  import { BaseEdge, type EdgeProps } from '@xyflow/svelte';

  let { id, sourceX, sourceY, targetX, targetY }: EdgeProps = $props();

  const centerY = $derived((targetY - sourceY) / 2 + sourceY);

  const edgePath = $derived(
    `M ${sourceX} ${sourceY} L ${sourceX} ${centerY} L ${targetX} ${centerY} L ${targetX} ${targetY}`,
  );
</script>

<BaseEdge {id} path={edgePath} />

// apps/example-apps/react/learn/custom-edge-path/StepEdge.jsx
import { BaseEdge } from '@xyflow/react';

export default function StepEdge({ id, sourceX, sourceY, targetX, targetY }) {
  const centerY = (targetY - sourceY) / 2 + sourceY;

  const edgePath = `M ${sourceX} ${sourceY} L ${sourceX} ${centerY} L ${targetX} ${centerY} L ${targetX} ${targetY}`;

  return (
    <>
      <BaseEdge id={id} path={edgePath} />
    </>
  );
}
