// apps/example-apps/react/examples/interaction/computing-flows/ResultNode.tsx
import { memo } from 'react';
import {
  Handle,
  Position,
  useNodeConnections,
  useNodesData,
} from '@xyflow/react';
import { isTextNode, type MyNode } from './initialElements';

function ResultNode() {
  const connections = useNodeConnections({
    handleType: 'target',
  });
  const nodesData = useNodesData<MyNode>(
    connections.map((connection) => connection.source),
  );
  const textNodes = nodesData.filter(isTextNode);

  return (
    <div>
      <Handle type="target" position={Position.Left} />
      <div>
        incoming texts:{' '}
        {textNodes.map(({ data }, i) => <div key={i}>{data.text}</div>) ||
          'none'}
      </div>
    </div>
  );
}

export default memo(ResultNode);

// apps/example-apps/svelte/examples/interaction/computing-flows/ResultNode.svelte
<script module>
  export type ResultNodeType = Node<{}, 'result'>;
</script>

<script lang="ts">
  import {
    Handle,
    Position,
    useNodeConnections,
    useNodesData,
    type NodeProps,
    type Node,
  } from '@xyflow/svelte';

  let { id }: NodeProps<ResultNodeType> = $props();

  const connections = useNodeConnections({
    id,
    handleType: 'target',
  });

  const nodesData = useNodesData(
    connections.current.map((connection) => connection.source),
  );
</script>

<div class="custom">
  <Handle type="target" position={Position.Left} />
  <div class="label">incoming texts:</div>

  {#if nodesData.current.length === 0}
    <div>no connected nodes</div>
  {:else}
    {#each nodesData.current as nodeData}
      <div>{nodeData.data.text}</div>
    {/each}
  {/if}
</div>

<style>
  .label {
    margin-bottom: 5px;
  }
</style>
