// sites/reactflow.dev/src/components/example-viewer/example-flows/ComputingFlows/TextNode.tsx
import { memo } from 'react';
import { Position, NodeProps, Handle, useReactFlow } from '@xyflow/react';

function TextNode({ id, data }: NodeProps) {
  const { updateNodeData } = useReactFlow();

  return (
    <div
      style={{
        background: '#eee',
        color: '#222',
        padding: 10,
        fontSize: 12,
        borderRadius: 10,
      }}
    >
      <div>node {id}</div>
      <div style={{ marginTop: 5 }}>
        <input
          onChange={(evt) => updateNodeData(id, { text: evt.target.value })}
          value={data.text}
          style={{ display: 'block' }}
        />
      </div>
      <Handle type="source" position={Position.Right} />
    </div>
  );
}

export default memo(TextNode);

// apps/example-apps/svelte/examples/interaction/computing-flows/TextNode.svelte
<script module>
  export type TextNodeType = Node<{ text: string }, 'text'>;
</script>

<script lang="ts">
  import {
    Handle,
    Position,
    useSvelteFlow,
    type NodeProps,
    type Node,
  } from '@xyflow/svelte';

  let { id, data }: NodeProps<TextNodeType> = $props();

  const { updateNodeData } = useSvelteFlow();
</script>

<div class="custom">
  <div class="label">text</div>
  <div>
    <input
      value={data.text}
      oninput={(evt) => updateNodeData(id, { text: evt.currentTarget.value })}
    />
  </div>
  <Handle type="source" position={Position.Right} />
</div>

<style>
  .custom {
    background-color: #eee;
    padding: 10px;
    border-radius: 10px;
  }

  .label {
    font-size: 12px;
    margin-bottom: 5px;
  }
</style>
