// sites/reactflow.dev/src/components/example-viewer/example-flows/DragHandle/index.jsx
import React from 'react';
import ReactFlow, { useNodesState, useEdgesState, Background } from 'reactflow';
import 'reactflow/dist/style.css';

import DragHandleNode from './DragHandleNode';

const nodeTypes = {
  dragHandleNode: DragHandleNode,
};

const initialNodes = [
  {
    id: '2',
    type: 'dragHandleNode',

    // Specify the custom class acting as a drag handle
    dragHandle: '.custom-drag-handle',

    style: {
      border: '1px solid #ddd',
      padding: '20px 40px',
      background: 'white',
    },
    position: { x: 200, y: 200 },
  },
];

const DragHandleFlow = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      nodeTypes={nodeTypes}
      fitView
    >
      <Background />
    </ReactFlow>
  );
};

export default DragHandleFlow;

// apps/svelte-examples/src/routes/examples/nodes/drag-handle/+page.svelte
<script lang="ts">
  import { writable } from 'svelte/store';
  import { SvelteFlow, Controls, Background, type Node, type Edge } from '@xyflow/svelte';

  import DragHandleNode from './DragHandleNode.svelte';

  import '@xyflow/svelte/dist/style.css';

  const nodeTypes = {
    dragHandleNode: DragHandleNode
  };

  const nodes = writable<Node[]>([
    {
      id: '2',
      type: 'dragHandleNode',
      dragHandle: '.custom-drag-handle',
      style: 'border: 1px solid #ddd; padding: 20px 40px; background: white;',
      position: { x: 200, y: 200 },
      data: {
        label: 'Drag Handle'
      }
    }
  ]);

  const edges = writable<Edge[]>([]);
</script>

<div style="height:100vh">
  <SvelteFlow {nodes} {edges} {nodeTypes} fitView>
    <Controls />
    <Background />
  </SvelteFlow>
</div>
