// apps/example-apps/svelte/examples/misc/threlte-flow/ColorPickerNode.svelte
<script lang="ts">
  import { Handle, Position, type NodeProps, type Node } from '@xyflow/svelte';
  import NodeWrapper from './NodeWrapper.svelte';
  import { flowState, type NodeData } from './nodes-and-edges.svelte';

  let { data }: NodeProps<Node<NodeData>> = $props();
</script>

<NodeWrapper label={data.label}>
  <div class="flex items-center space-x-2 p-3">
    <input
      bind:value={flowState.color}
      class="nodrag border-md w-6 h-6"
      type="color"
    />
    <p>{flowState.color}</p>
  </div>
  <Handle type="source" position={Position.Right} />
</NodeWrapper>

// packages/xy-ui/components/widgets/hero-flow/color-picker-node.tsx
import { memo } from 'react';
import { Position } from 'reactflow';

import { Text } from '../../..';
import Handle from './handle';
import Wrapper from './node-wrapper';

export default memo(({ data }: { data: any }) => {
  const { label = '', onChange = () => {}, color = '#000', value } = data;

  return (
    <Wrapper label={label}>
      <div className="flex items-center space-x-2">
        <input
          className="nodrag border-md w-6 h-6"
          type="color"
          onChange={(evt) => onChange(evt.target.value)}
          defaultValue={color}
        />
        <Text size="xs" variant="light">
          {value || color}
        </Text>
      </div>
      <Handle type="source" position={Position.Right} />
    </Wrapper>
  );
});
