// apps/example-apps/svelte/examples/nodes/drag-handle/DragHandleNode.svelte
<script lang="ts">
  import { Handle, Position, type NodeProps } from '@xyflow/svelte';

  let {}: NodeProps = $props();
</script>

<Handle type="target" position={Position.Left} />
<div class="label">
  Only draggable here →
  <!-- Use the class specified at node.dragHandle here -->
  <span class="drag-handle custom-drag-handle" />
</div>
<Handle type="source" position={Position.Right} />

<style>
  .label {
    display: flex;
    align-items: center;
  }

  .drag-handle {
    display: inline-block;
    width: 25px;
    height: 25px;
    background-color: teal;
    margin-left: 5px;
    border-radius: 50%;
  }
</style>

// apps/example-apps/react/examples/nodes/drag-handle/DragHandleNode.jsx
import { memo } from 'react';
import { Handle, Position } from '@xyflow/react';

const onConnect = (params) => console.log('handle onConnect', params);

function DragHandleNode() {
  return (
    <>
      <Handle type="target" position={Position.Left} onConnect={onConnect} />
      <div className="drag-handle__label">
        Only draggable here →{/* Use the class specified at node.dragHandle here */}
        <span className="drag-handle__custom" />
      </div>
      <Handle type="source" position={Position.Right} />
    </>
  );
}

export default memo(DragHandleNode);
