// apps/example-apps/svelte/examples/interaction/computing-flows/TextNode.svelte
<script module>
  export type TextNodeType = Node<{ text: string }, 'text'>;
</script>

<script lang="ts">
  import {
    Handle,
    Position,
    useSvelteFlow,
    type NodeProps,
    type Node,
  } from '@xyflow/svelte';

  let { id, data }: NodeProps<TextNodeType> = $props();

  const { updateNodeData } = useSvelteFlow();
</script>

<div class="custom">
  <div class="label">text</div>
  <div>
    <input
      class="xy-theme__input"
      value={data.text}
      oninput={(evt) => updateNodeData(id, { text: evt.currentTarget.value })}
    />
  </div>
  <Handle type="source" position={Position.Right} />
</div>

<style>
  .label {
    font-size: 12px;
    margin-bottom: 5px;
  }
</style>

// apps/example-apps/react/examples/interaction/computing-flows/TextNode.tsx
import { memo } from 'react';
import { Position, Handle, useReactFlow, type NodeProps, type Node } from '@xyflow/react';

function TextNode({ id, data }: NodeProps<Node<{ text: string }>>) {
  const { updateNodeData } = useReactFlow();

  return (
    <div>
      <div>node {id}</div>
      <div>
        <input
          onChange={(evt) => updateNodeData(id, { text: evt.target.value })}
          value={data.text}
          className="xy-theme__input"
        />
      </div>
      <Handle type="source" position={Position.Right} />
    </div>
  );
}

export default memo(TextNode);
