// apps/example-apps/svelte/examples/interaction/computing-flows/UppercaseNode.svelte
<script lang="ts">
  import {
    Handle,
    Position,
    useNodeConnections,
    useNodesData,
    useSvelteFlow,
    type NodeProps
  } from '@xyflow/svelte';

  type $$Props = NodeProps;

  export let id: $$Props['id'];

  const { updateNodeData } = useSvelteFlow();
  const connections = useNodeConnections({
    id,
    handleType: 'target'
  });

  $: nodeData = useNodesData($connections[0]?.source);
  $: {
    updateNodeData(id, { text: $nodeData?.data?.text?.toUpperCase() || '' });
  }
</script>

<div class="custom">
  <Handle type="target" position={Position.Left} isConnectable={$connections.length === 0} />
  <div>uppercase transform</div>
  <Handle type="source" position={Position.Right} />
</div>

<style>
  .custom {
    background-color: #eee;
    padding: 10px;
    border-radius: 10px;
    font-size: 12px;
  }
</style>

// apps/example-apps/react/examples/interaction/computing-flows/UppercaseNode.tsx
import { memo, useEffect } from 'react';
import {
  Position,
  Handle,
  useReactFlow,
  useHandleConnections,
  useNodesData,
  type NodeProps,
} from '@xyflow/react';

import { isTextNode, type MyNode } from './utils';

function UppercaseNode({ id }: NodeProps) {
  const { updateNodeData } = useReactFlow();
  const connections = useHandleConnections({
    type: 'target',
  });
  const nodesData = useNodesData<MyNode>(connections[0]?.source);
  const textNode = isTextNode(nodesData) ? nodesData : null;

  useEffect(() => {
    updateNodeData(id, { text: textNode?.data.text.toUpperCase() });
  }, [textNode]);

  return (
    <div
      style={{
        background: '#eee',
        color: '#222',
        padding: 10,
        fontSize: 12,
        borderRadius: 10,
      }}
    >
      <Handle
        type="target"
        position={Position.Left}
        isConnectable={connections.length === 0}
      />
      <div>uppercase transform</div>
      <Handle type="source" position={Position.Right} />
    </div>
  );
}

export default memo(UppercaseNode);
