// apps/example-apps/svelte/guides/custom-nodes-multiple-handles/TextUpdaterNode.svelte
<script lang="ts">
  import { Handle, Position } from '@xyflow/svelte';

  export let data;
  export let isConnectable;

  const handleStyle = 'left: 10px';

  function onChange(evt: Event) {
    console.log((evt.target as HTMLInputElement).value);
  }
</script>

<div class="text-updater-node">
  <Handle type="target" position={Position.Top} {isConnectable} />
  <div>
    <label for="text">Text:</label>
    <input id="text" name="text" on:change={onChange} class="nodrag" />
  </div>
  <Handle
    type="source"
    position={Position.Bottom}
    id="a"
    style={handleStyle}
    {isConnectable}
  />
  <Handle type="source" position={Position.Bottom} id="b" {isConnectable} />
</div>

<style>
  .text-updater-node {
    height: 50px;
    border: 1px solid #eee;
    padding: 5px;
    border-radius: 5px;
    background: white;
  }

  .text-updater-node label {
    display: block;
    color: #777;
    font-size: 12px;
  }
</style>

// apps/example-apps/react/learn/custom-node-2/TextUpdaterNode.jsx
import { useCallback } from 'react';
import { Handle, Position } from '@xyflow/react';

const handleStyle = { left: 10 };

function TextUpdaterNode({ data, isConnectable }) {
  const onChange = useCallback((evt) => {
    console.log(evt.target.value);
  }, []);

  return (
    <div className="text-updater-node">
      <Handle
        type="target"
        position={Position.Top}
        isConnectable={isConnectable}
      />
      <div>
        <label htmlFor="text">Text:</label>
        <input id="text" name="text" onChange={onChange} className="nodrag" />
      </div>
      <Handle
        type="source"
        position={Position.Bottom}
        id="a"
        style={handleStyle}
        isConnectable={isConnectable}
      />
      <Handle
        type="source"
        position={Position.Bottom}
        id="b"
        isConnectable={isConnectable}
      />
    </div>
  );
}

export default TextUpdaterNode;
