// apps/example-apps/svelte/examples/misc/threlte-flow/SwitcherNode.svelte
<script lang="ts">
  import { Handle, type Node, Position, type NodeProps } from '@xyflow/svelte';
  import NodeWrapper from './NodeWrapper.svelte';
  import { flowState, type NodeData } from './nodes-and-edges.svelte';

  let { data }: NodeProps<Node<NodeData>> = $props();

  const options = ['cube', 'pyramid'];
</script>

<NodeWrapper label={data.label}>
  <Handle
    type="source"
    position={Position.Right}
    class="w-[10px] h-[10px] border-none bg-gray-400"
  />
  <div class="flex flex-col nodrag p-3 gap-1.5">
    {#each options as option}
      <label class="flex items-center gap-2 cursor-pointer">
        <input
          bind:group={flowState.shape}
          class="accent-[#ff4000]"
          type="radio"
          value={option}
          checked={flowState.shape === option}
        />
        <span class="text-xs text-gray-700 dark:text-gray-300">{option}</span>
      </label>
    {/each}
  </div>
</NodeWrapper>

// packages/xy-shared/components/flows/hero-flow/switcher-node.tsx
import { useCallback } from 'react';
import { Node, NodeProps, Position, useReactFlow } from '@xyflow/react';
import { RadioGroup, RadioGroupItem } from '../../../components/ui/radio-group';
import { Label } from '../../../components/ui/label';

import Handle from './handle';
import Wrapper from './node-wrapper';

const options = [
  { label: 'cube', value: 'cube' },
  { label: 'pyramid', value: 'tetrahedron' },
];

export type SwitcherNode = Node<{
  label: 'cube' | 'pyramid';
  value: 'cube' | 'tetrahedron';
}>;

export default function SwitcherNode({ id, data }: NodeProps<SwitcherNode>) {
  const { updateNodeData } = useReactFlow();
  const onValueChange = useCallback(
    (value: string) => updateNodeData(id, { value }),
    [id, updateNodeData],
  );

  return (
    <Wrapper label={data.label}>
      <Handle type="source" position={Position.Right} />
      <RadioGroup value={data.value} onValueChange={onValueChange}>
        {options.map((option) => (
          <div className="nodrag flex items-center space-x-2" key={option.value}>
            <RadioGroupItem
              value={option.value}
              id={option.value}
              className="text-primary border-primary"
            />
            <Label htmlFor={option.value} className="text-light cursor-pointer text-xs">
              {option.label}
            </Label>
          </div>
        ))}
      </RadioGroup>
    </Wrapper>
  );
}
