// apps/example-apps/react/examples/misc/overview/CircleNode.jsx
import React, { memo } from 'react';
import { Handle, Position } from '@xyflow/react';

export default memo(({ id, positionAbsoluteX, positionAbsoluteY }) => {
  const label = `Position x:${Math.round(positionAbsoluteX)} y:${Math.round(positionAbsoluteY)}`;

  return (
    <div>
      <div>{label || 'no node connected'}</div>
      <Handle
        type="target"
        position={Position.Left}
        className="custom-handle"
      />
    </div>
  );
});

// apps/svelte-examples/src/routes/examples/feature-overview/CircleNode.svelte
<script lang="ts">
  import { type NodeProps, Handle, Position } from '@xyflow/svelte';

  import type { CircleNode } from './types';

  type $$Props = NodeProps<CircleNode>;

  export let positionAbsoluteX: $$Props['positionAbsoluteX'];
  export let positionAbsoluteY: $$Props['positionAbsoluteY'];
  $$restProps;

  $: label = `position x:${Math.round(positionAbsoluteX)} y:${Math.round(positionAbsoluteY)}`;
</script>

<div class="wrapper gradient">
  <div class="inner">{label || 'no node connected'}</div>
</div>
<Handle type="target" position={Position.Left} />
