// sites/reactflow.dev/src/components/example-viewer/example-flows/Stress/index.jsx
import React, { useCallback } from 'react';
import {
  ReactFlow,
  useNodesState,
  useEdgesState,
  addEdge,
  MiniMap,
  Controls,
  Background,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';

import { createNodesAndEdges } from './utils.js';

const { nodes: initialNodes, edges: initialEdges } = createNodesAndEdges(
  15,
  30,
);

const StressFlow = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);
  const onConnect = useCallback(
    (params) => setEdges((els) => addEdge(params, els)),
    [],
  );

  const updatePos = useCallback(() => {
    setNodes((nds) => {
      return nds.map((node) => {
        return {
          ...node,
          position: {
            x: Math.random() * 1500,
            y: Math.random() * 1500,
          },
        };
      });
    });
  }, []);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onConnect={onConnect}
      fitView
      minZoom={0}
    >
      <MiniMap />
      <Controls />
      <Background />

      <button
        onClick={updatePos}
        style={{ position: 'absolute', right: 10, top: 30, zIndex: 4 }}
      >
        change pos
      </button>
    </ReactFlow>
  );
};

export default StressFlow;

// apps/svelte-examples/src/routes/examples/nodes/stress/+page.svelte
<script>
  import { SvelteFlow, Background, Controls, MiniMap } from '@xyflow/svelte';
  import { writable } from 'svelte/store';
  import { createNodesAndEdges } from './utils';

  import '@xyflow/svelte/dist/style.css';

  const { nodes: initialNodes, edges: initialEdges } = createNodesAndEdges(15, 30);
  const nodes = writable(initialNodes);
  const edges = writable(initialEdges);

  function updatePos() {
    $nodes.forEach((node) => {
      node.position = {
        x: Math.random() * 1500,
        y: Math.random() * 1500
      };
    });
    $nodes = $nodes;
  }
</script>

<div style="height:100vh;">
  <SvelteFlow {nodes} {edges} minZoom={0} fitView>
    <Background />
    <MiniMap />
    <Controls />
    <button on:click={updatePos} class="scramble-button"> change pos </button>
  </SvelteFlow>
</div>

<style>
  .scramble-button {
    position: absolute;
    right: 10px;
    top: 30px;
    z-index: 4;
  }
</style>
