// apps/example-apps/react/examples/styling/tailwind/CustomNode.jsx
import { memo } from 'react';
import { Handle, Position } from '@xyflow/react';

function CustomNode({ data }) {
  return (
    <div className="rounded-md border-2 border-stone-400 bg-white px-4 py-2 shadow-md dark:border-gray-600 dark:bg-gray-800">
      <div className="flex">
        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-teal-100 text-center dark:bg-gray-700">
          <span className="translate-x-[2px]">{data.emoji}</span>
        </div>
        <div className="ml-2">
          <div className="text-lg font-bold text-gray-900 dark:text-gray-100">
            {data.name}
          </div>
          <div className="text-gray-500 dark:text-gray-400">{data.job}</div>
        </div>
      </div>

      <Handle
        type="target"
        position={Position.Top}
        className="w-16 rounded-none border-none bg-teal-500 dark:bg-teal-400"
      />
      <Handle
        type="source"
        position={Position.Bottom}
        className="w-16 rounded-none border-none bg-teal-500 dark:bg-teal-400"
      />
    </div>
  );
}

export default memo(CustomNode);

// apps/example-apps/svelte/examples/styling/tailwind/CustomNode.svelte
<script lang="ts">
  import { Handle, Position, type NodeProps } from '@xyflow/svelte';

  let { data }: NodeProps = $props();
</script>

<div
  class="px-4 py-2 shadow-md rounded-md bg-white dark:bg-gray-800 border-2 border-stone-400 dark:border-gray-600"
>
  <div class="flex">
    <div
      class="rounded-full w-12 h-12 flex justify-center items-center bg-teal-100 dark:bg-gray-700"
    >
      <span class="translate-x-[2px]">{data.emoji}</span>
    </div>
    <div class="ml-2">
      <div class="text-lg font-bold text-gray-900 dark:text-gray-100">{data.name}</div>
      <div class="text-gray-500 dark:text-gray-400">{data.job}</div>
    </div>
  </div>
  <Handle
    type="target"
    position={Position.Top}
    class="w-16 h-2 bg-teal-500 dark:bg-teal-400 rounded-none border-none"
  />
  <Handle
    type="source"
    position={Position.Bottom}
    class="w-16 h-2 bg-teal-500 dark:bg-teal-400 rounded-none border-none"
  />
</div>
