// apps/svelte-examples/src/routes/examples/edges/custom-connectionline/+page.svelte
<script lang="ts">
  import { SvelteFlow } from '@xyflow/svelte';
  import { Background, BackgroundVariant, type Edge, type Node } from '@xyflow/svelte';
  import { writable } from 'svelte/store';

  import CustomNode from './CustomNode.svelte';
  import ConnectionLine from './ConnectionLine.svelte';

  import '@xyflow/svelte/dist/style.css';

  const nodeTypes = {
    custom: CustomNode
  };

  const nodes = writable<Node[]>([
    {
      id: 'connectionline-1',
      type: 'custom',
      data: { label: 'Node 1' },
      position: { x: 250, y: 5 }
    }
  ]);

  const edges = writable<Edge[]>([]);
</script>

<div style="height:100vh;">
  <SvelteFlow {nodeTypes} {nodes} {edges} fitView>
    <Background variant={BackgroundVariant.Lines} />
  </SvelteFlow>
</div>

<style>
</style>

// sites/reactflow.dev/src/components/example-viewer/example-flows/CustomConnectionLine/index.jsx
import React, { useCallback } from 'react';
import {
  ReactFlow,
  useNodesState,
  useEdgesState,
  addEdge,
  Background,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';

import CustomNode from './CustomNode';
import ConnectionLine from './ConnectionLine';

const initialNodes = [
  {
    id: 'connectionline-1',
    type: 'custom',
    data: { label: 'Node 1' },
    position: { x: 250, y: 5 },
  },
];

const nodeTypes = {
  custom: CustomNode,
};

const ConnectionLineFlow = () => {
  const [nodes, _, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);
  const onConnect = useCallback(
    (params) => setEdges((eds) => addEdge(params, eds)),
    [],
  );

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      nodeTypes={nodeTypes}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      connectionLineComponent={ConnectionLine}
      onConnect={onConnect}
      fitView
      fitViewOptions={{
        padding: 0.2,
      }}
    >
      <Background variant="lines" />
    </ReactFlow>
  );
};

export default ConnectionLineFlow;
