// apps/example-apps/react/examples/interaction/context-menu/ContextMenu.jsx
import { useCallback } from 'react';
import { useReactFlow } from '@xyflow/react';

export default function ContextMenu({ id, top, left, right, bottom, ...props }) {
  const { getNode, setNodes, addNodes, setEdges } = useReactFlow();
  const duplicateNode = useCallback(() => {
    const node = getNode(id);
    const position = {
      x: node.position.x + 50,
      y: node.position.y + 50,
    };

    addNodes({
      ...node,
      selected: false,
      dragging: false,
      id: `${node.id}-copy`,
      position,
    });
  }, [id, getNode, addNodes]);

  const deleteNode = useCallback(() => {
    setNodes((nodes) => nodes.filter((node) => node.id !== id));
    setEdges((edges) => edges.filter((edge) => edge.source !== id));
  }, [id, setNodes, setEdges]);

  return (
    <div style={{ top, left, right, bottom }} className="context-menu" {...props}>
      <p style={{ margin: '0.5em' }}>
        <small>node: {id}</small>
      </p>
      <button onClick={duplicateNode}>duplicate</button>
      <button onClick={deleteNode}>delete</button>
    </div>
  );
}

// apps/example-apps/svelte/examples/interaction/context-menu/ContextMenu.svelte
<script lang="ts">
  import { useEdges, useNodes, useSvelteFlow } from '@xyflow/svelte';

  let {
    id,
    top,
    left,
    right,
    bottom,
    onclick,
  }: {
    id: string;
    top: number | undefined;
    left: number | undefined;
    right: number | undefined;
    bottom: number | undefined;
    onclick: () => void;
  } = $props();

  const { deleteElements } = useSvelteFlow();

  const nodes = useNodes();

  function duplicateNode() {
    const node = nodes.current.find((node) => node.id === id);
    if (node) {
      nodes.current = [
        ...nodes.current,
        {
          ...node,
          // You should use a better id than this in production
          id: `${id}-copy${Math.random()}`,
          position: {
            x: node.position.x,
            y: node.position.y + 50,
          },
        },
      ];
    }
  }

  function deleteNode() {
    deleteElements({ nodes: [{ id }] });
  }
</script>

<div
  style="top: {top}px; left: {left}px; right: {right}px; bottom: {bottom}px;"
  class="context-menu"
  {onclick}
>
  <p style="margin: 0.5em;">
    <small>node: {id}</small>
  </p>
  <button onclick={duplicateNode}>duplicate</button>
  <button onclick={deleteNode}>delete</button>
</div>

<style>
  .context-menu {
    background: white;
    border-style: solid;
    box-shadow: 10px 19px 20px rgba(0, 0, 0, 10%);
    position: absolute;
    z-index: 10;
  }

  .context-menu button {
    border: none;
    display: block;
    padding: 0.5em;
    text-align: left;
    width: 100%;
  }

  .context-menu button:hover {
    background: white;
  }
</style>
