// apps/example-apps/react/examples/misc/download-image/CustomNode.jsx
import { memo } from 'react';
import { Handle, Position } from '@xyflow/react';

export default memo(({ data, isConnectable }) => {
  return (
    <>
      <Handle
        type="target"
        position={Position.Left}
        onConnect={(params) => console.log('handle onConnect', params)}
        isConnectable={isConnectable}
      />
      <div>▼</div>

      <Handle
        type="source"
        position={Position.Right}
        id="a"
        style={{ top: 5 }}
        isConnectable={isConnectable}
      />
      <Handle
        type="source"
        position={Position.Right}
        id="b"
        style={{ bottom: 5, top: 'auto' }}
        isConnectable={isConnectable}
      />
    </>
  );
});

// apps/docs/src/components/code-viewer/svelte/guides/custom-nodes/a/custom-node.svelte
<script>
  import { Handle, Position } from '@xyflow/svelte';

  export let data = {
    color: '#111',
    onChange: () => {},
  };
</script>

<Handle type="target" position={Position.Left} />
<div>
  Custom Color Picker Node: <strong>{data.color}</strong>
</div>
<input
  class="nodrag"
  type="color"
  on:input={data.onChange}
  value={data.color}
/>
<Handle type="source" position={Position.Right} id="a" style="top: 10px;" />
<Handle
  type="source"
  position={Position.Right}
  id="b"
  style="top: auto; bottom: 10px;"
/>
