// apps/example-apps/react/examples/whiteboard/eraser/ErasableNode.tsx
import { Handle, Position, type Node, type NodeProps } from '@xyflow/react';

export type ErasableNodeType = Node<
  { toBeDeleted?: boolean; label?: string },
  'erasable-node'
>;

export function ErasableNode({
  data: { label, toBeDeleted },
}: NodeProps<ErasableNodeType>) {
  return (
    <div style={{ opacity: toBeDeleted ? 0.3 : 1 }}>
      <Handle type="target" position={Position.Top} />
      <div style={{ padding: 10 }}>{label}</div>
      <Handle type="source" position={Position.Bottom} />
    </div>
  );
}

// apps/example-apps/svelte/examples/whiteboard/eraser/ErasableNode.svelte
<script module>
  import { type Node } from '@xyflow/svelte';

  export type ErasableNodeType = Node<
    {
      toBeDeleted?: boolean;
      label?: string;
    },
    'erasable-node'
  >;
</script>

<script lang="ts">
  import { Handle, Position, type NodeProps } from '@xyflow/svelte';

  let { data, isConnectable }: NodeProps<ErasableNodeType> = $props();
</script>

<div style="opacity: {data.toBeDeleted ? 0.3 : 1}">
  <Handle type="target" position={Position.Top} {isConnectable} />
  <div style="padding: 10px">{data.label}</div>
  <Handle type="source" position={Position.Bottom} {isConnectable} />
</div>
