// apps/example-apps/react/examples/interaction/drag-and-drop/Sidebar.jsx
import React from 'react';
import { useDnD } from './DnDContext';

export default () => {
  const [_, setType] = useDnD();

  const onDragStart = (event, nodeType) => {
    setType(nodeType);
    event.dataTransfer.effectAllowed = 'move';
  };

  return (
    <aside>
      <div className="description">You can drag these nodes to the pane on the right.</div>
      <div className="dndnode input" onDragStart={(event) => onDragStart(event, 'input')} draggable>
        Input Node
      </div>
      <div className="dndnode" onDragStart={(event) => onDragStart(event, 'default')} draggable>
        Default Node
      </div>
      <div className="dndnode output" onDragStart={(event) => onDragStart(event, 'output')} draggable>
        Output Node
      </div>
    </aside>
  );
};

// sites/docs/src/components/code-viewer/svelte/examples/drag-and-drop/Sidebar.svelte
<script lang="ts">
  const onDragStart = (event: DragEvent, nodeType: string) => {
    if (!event.dataTransfer) {
      return null;
    }

    event.dataTransfer.setData('application/svelteflow', nodeType);
    event.dataTransfer.effectAllowed = 'move';
  };
</script>

<aside>
  <div class="label">You can drag these nodes to the pane on the left.</div>
  <div
    class="input-node node"
    on:dragstart={(event) => onDragStart(event, 'input')}
    draggable={true}
  >
    Input Node
  </div>
  <div
    class="default-node node"
    on:dragstart={(event) => onDragStart(event, 'default')}
    draggable={true}
  >
    Default Node
  </div>
  <div
    class="output-node node"
    on:dragstart={(event) => onDragStart(event, 'output')}
    draggable={true}
  >
    Output Node
  </div>
</aside>

<style>
  .label {
    margin: 0.5rem 0 0.25rem 0;
  }

  aside {
    width: 20vw;
    background: #f4f4f4;
    padding: 0.4rem 0.8rem;
    font-size: 12px;
  }

  .node {
    margin-bottom: 0.5rem;
    border: 1px solid #111;
    padding: 0.5rem 1rem;
    font-weight: 700;
    border-radius: 3px;
    cursor: grab;
  }
</style>
