// sites/reactflow.dev/src/components/example-viewer/example-flows/Overview/AnnotationNode.jsx
import { memo } from 'react';

function AnnotationNode({ data }) {
  return (
    <>
      <div style={{ padding: 10 }}>{data.label}</div>
      {data.arrowStyle && (
        <div className="arrow" style={data.arrowStyle}>
          ⤹
        </div>
      )}
    </>
  );
}

export default memo(AnnotationNode);

// apps/example-apps/svelte/examples/misc/feature-overview/AnnotationNode.svelte
<script module>
  import type { Node, NodeProps } from '@xyflow/svelte';

  export type AnnotationNode = Node<{
    label: string;
    level: number;
    arrowStyle?: string;
  }>;
</script>

<script lang="ts">
  let { data }: NodeProps<AnnotationNode> = $props();
</script>

<div style="padding: 10px; display: flex">
  <div style="marginRight: 4px">{data.level}.</div>
  <div>{data.label}</div>
</div>
{#if data.arrowStyle}
  <div class="arrow" style={data.arrowStyle}>⤹</div>
{/if}
