// apps/example-apps/react/examples/misc/overview/ResizerNode.jsx
import { memo } from 'react';
import { Handle, Position, NodeResizer } from '@xyflow/react';

function ResizerNode({ data }) {
  return (
    <>
      <NodeResizer minWidth={50} minHeight={50} />
      <Handle type="target" position={Position.Left} className='custom-handle' />
      <div>{data.label}</div>
      <div className="resizer-node__handles">
        <Handle
          className="resizer-node__handle custom-handle"
          id="a"
          type="source"
          position={Position.Bottom}
        />
        <Handle
          className="resizer-node__handle custom-handle "
          id="b"
          type="source"
          position={Position.Bottom}
        />
      </div>
    </>
  );
}

export default memo(ResizerNode);

// apps/example-apps/svelte/examples/misc/feature-overview/ResizerNode.svelte
<script lang="ts">
  import {
    Handle,
    NodeResizer,
    Position,
    type NodeProps,
  } from '@xyflow/svelte';

  let { data }: NodeProps = $props();
</script>

<NodeResizer minWidth={100} minHeight={30} />
<Handle type="target" position={Position.Left} class="custom-handle" />
<div>{data.label}</div>
<div class="resizer-node__handles">
  <Handle
    class="resizer-node__handle custom-handle"
    id="a"
    type="source"
    position={Position.Bottom}
  />
  <Handle
    class="resizer-node__handle custom-handle"
    id="b"
    type="source"
    position={Position.Bottom}
  />
</div>
