// apps/example-apps/react/examples/misc/overview/ToolbarNode.jsx
import { memo, useState } from 'react';
import { Handle, Position, NodeToolbar } from '@xyflow/react';

const labelStyle = {
  position: 'absolute',
  color: '#555',
  bottom: -15,
  fontSize: 8,
};

function ToolbarNode({ data }) {
  const [emoji, setEmoji] = useState(() => '🚀');

  return (
    <>
      <NodeToolbar isVisible>
        <button onClick={() => setEmoji('🚀')}>🚀</button>
        <button onClick={() => setEmoji('🔥')}>🔥</button>
        <button onClick={() => setEmoji('✨')}>✨</button>
      </NodeToolbar>
      <div>
        <div>{emoji}</div>
      </div>
      <Handle type="target" position={Position.Left} />
      <Handle type="source" position={Position.Right} />

      <div style={labelStyle}>{data.label}</div>
    </>
  );
}

export default memo(ToolbarNode);

// apps/example-apps/svelte/examples/misc/feature-overview/ToolbarNode.svelte
<script lang="ts">
  import {
    Handle,
    NodeToolbar,
    Position,
    type NodeProps,
  } from '@xyflow/svelte';
  import { writable } from 'svelte/store';

  let { data }: NodeProps = $props();

  const emoji = writable('🚀');
</script>

<NodeToolbar isVisible position={Position.Top}>
  <button onclick={() => emoji.set('🚀')}>🚀</button>
  <button onclick={() => emoji.set('🔥')}>🔥</button>
  <button onclick={() => emoji.set('✨')}>✨</button>
</NodeToolbar>
<div style="padding: 10px 20px">
  <div>{$emoji}</div>
</div>
<Handle type="target" position={Position.Left} />
<Handle type="source" position={Position.Right} />

<div style="position: absolute; color: #555; bottom: -15px; fontSize: 8px;">
  {data.label}
</div>
