// apps/svelte-examples/src/routes/examples/misc/hero-flow/ColorPickerNode.svelte
<script lang="ts">
  import { Handle, Position, type NodeProps } from '@xyflow/svelte';
  import NodeWrapper from './NodeWrapper.svelte';
  import type { NodeData } from './nodes-and-edges';

  type $$Props = NodeProps;
  export let data: NodeData;
  const { label, flowState } = data;

  let value = $flowState.color;
  $: {
    $flowState.color = value;
  }
</script>

<NodeWrapper {label}>
  <div class="flex items-center space-x-2">
    <input bind:value class="nodrag border-md w-6 h-6" type="color" />
    <p>{value}</p>
  </div>
  <Handle type="source" position={Position.Right} on:connect on:connectend on:connectstart />
</NodeWrapper>

// packages/xy-shared/widgets/hero-flow/color-picker-node.tsx
import { memo } from 'react';
import { NodeProps, Position, useReactFlow } from '@xyflow/react';
import { Text } from '@xyflow/xy-ui';

import Handle from './handle';
import Wrapper from './node-wrapper';

export default memo(({ data, id }: NodeProps) => {
  const { updateNodeData } = useReactFlow();

  return (
    <Wrapper label={data.label}>
      <div className="flex items-center space-x-2">
        <input
          className="nodrag border-md w-6 h-6"
          type="color"
          onChange={(evt) => updateNodeData(id, { value: evt.target.value })}
          defaultValue={data.value}
        />
        <Text size="xs" variant="light">
          {data.value}
        </Text>
      </div>
      <Handle type="source" position={Position.Right} />
    </Wrapper>
  );
});
