// apps/example-apps/svelte/learn/basic-terms/AnnotationNode.svelte
<script module>
  import type { Node, NodeProps } from '@xyflow/svelte';
  import { MoveDown } from '@lucide/svelte';

  export type AnnotationNode = Node<{
    label: string;
    arrowStyle?: string;
  }>;
</script>

<script lang="ts">
  let { data }: NodeProps<AnnotationNode> = $props();
</script>

<div class="annotation-content">
  <div>{data.label}</div>
</div>
{#if data.arrowStyle}
  <div class="annotation-arrow {data.arrowStyle}"><MoveDown /></div>
{/if}

// apps/example-apps/react/learn/basic-terms/AnnotationNode.jsx
import { memo } from 'react';
import { MoveDown } from 'lucide-react';

function AnnotationNode({ data }) {
  return (
    <>
      <div className="annotation-content">
        <div>{data.label}</div>
      </div>
      {data.arrowStyle && (
        <div className={`annotation-arrow ${data.arrowStyle}`}>
          <MoveDown />
        </div>
      )}
    </>
  );
}

export { AnnotationNode };
export default memo(AnnotationNode);
