// apps/example-apps/react/examples/edges/simple-floating-edges/CustomNode.jsx
import React, { memo } from 'react';
import { Handle, Position } from '@xyflow/react';

export default memo(({ data }) => {
  return (
    <>
      {data.label}
      <Handle type="source" position={Position.Top} id="a" />
      <Handle type="source" position={Position.Right} id="b" />
      <Handle type="source" position={Position.Bottom} id="c" />
      <Handle type="source" position={Position.Left} id="d" />
    </>
  );
});

// sites/svelteflow.dev/src/components/example-viewer/svelte/examples/overview/CustomNode.svelte
<script>
  import { Handle, Position } from '@xyflow/svelte';

  export let data = { label: 'Node' };
  export let xPos = 0;
  export let yPos = 0;
</script>

<div class="custom">
  <div>{data.label}</div>
  <div>{~~xPos}, {~~yPos}</div>

  <Handle type="target" position={Position.Top} />

  <Handle type="source" position={Position.Bottom} style="left: 10%;" id="a" />
  <Handle type="source" position={Position.Bottom} id="b" />
  <Handle type="source" position={Position.Bottom} style="left: 90%;" id="c" />
</div>

<style>
  .custom {
    background: #ffcc00;
    padding: 10px;
  }
</style>
