// sites/reactflow.dev/src/components/example-viewer/example-flows/ComputingFlows/ResultNode.tsx
import { memo } from 'react';
import {
  Handle,
  Position,
  useHandleConnections,
  useNodesData,
} from '@xyflow/react';
import { isTextNode, type MyNode } from './utils';

function ResultNode() {
  const connections = useHandleConnections({
    type: 'target',
  });
  const nodesData = useNodesData<MyNode>(
    connections.map((connection) => connection.source),
  );

  const textNodes = nodesData.filter(isTextNode);

  return (
    <div
      style={{
        background: '#eee',
        color: '#222',
        padding: 10,
        fontSize: 12,
        borderRadius: 10,
      }}
    >
      <Handle type="target" position={Position.Left} />
      <div>
        incoming texts:{' '}
        {textNodes.map(({ data }, i) => <div key={i}>{data.text}</div>) ||
          'none'}
      </div>
    </div>
  );
}

export default memo(ResultNode);

// apps/svelte-examples/src/routes/examples/interaction/reactive-flow/ResultNode.svelte
<script lang="ts">
  import {
    Handle,
    Position,
    useHandleConnections,
    useNodesData,
    type NodeProps
  } from '@xyflow/svelte';

  type $$Props = NodeProps;

  export let id: $$Props['id'];

  const connections = useHandleConnections({
    nodeId: id,
    type: 'target'
  });

  $: nodesData = useNodesData($connections.map((connection) => connection.source));
</script>

<div class="custom">
  <Handle type="target" position={Position.Left} />
  <div class="label">incoming texts:</div>

  {#if $nodesData.length === 0}
    <div>no connected nodes</div>
  {:else}
    {#each $nodesData as nodeData}
      <div>{nodeData.data.text}</div>
    {/each}
  {/if}
</div>

<style>
  .custom {
    background-color: #eee;
    padding: 10px;
    border-radius: 10px;
    font-size: 12px;
  }

  .label {
    margin-bottom: 5px;
  }
</style>
