// sites/docs/src/components/code-viewer/svelte/examples/subflows/index.svelte
<script lang="ts">
  import { writable } from 'svelte/store';
  import {
    SvelteFlow,
    Controls,
    Background,
    BackgroundVariant,
    MiniMap,
    type NodeTypes,
    type Node,
  } from '@xyflow/svelte';

  import DebugNode from './DebugNode.svelte';

  import '@xyflow/svelte/dist/style.css';

  const nodeTypes: NodeTypes = {
    default: DebugNode,
  };

  const nodes = writable<Node[]>([
    {
      id: '1',
      type: 'input',
      data: { label: 'Node 1' },
      position: { x: 250, y: 5 },
      origin: [0.5, 0.5],
    },
    {
      id: '4',
      data: { label: 'Node 4' },
      position: { x: 100, y: 200 },
      style: 'width:500px; height:300px;',
    },
    {
      id: '4a',
      data: { label: 'Node 4a' },
      position: { x: 15, y: 15 },
      parentNode: '4',
      extent: [
        [0, 0],
        [100, 100],
      ],
    },
    {
      id: '4b',
      data: { label: 'Node 4b' },
      position: { x: 100, y: 60 },
      style: 'width: 300px; height: 200px;',
      parentNode: '4',
    },
    {
      id: '4b1',
      data: { label: 'Node 4b1' },
      position: { x: 40, y: 20 },
      parentNode: '4b',
    },
    {
      id: '4b2',
      data: { label: 'Node 4b2' },
      position: { x: 20, y: 100 },
      parentNode: '4b',
    },
    {
      id: '5',
      type: 'group',
      data: { label: 'Node 5' },
      position: { x: 650, y: 250 },
      style: 'width: 400px; height: 150px',
      zIndex: 1000,
    },
    {
      id: '5a',
      data: { label: 'Node 5a' },
      position: { x: 0, y: 0 },
      parentNode: '5',
      extent: 'parent',
    },
    {
      id: '5b',
      data: { label: 'Node 5b' },
      position: { x: 225, y: 50 },
      parentNode: '5',
      expandParent: true,
    },
    {
      id: '2',
      data: { label: 'Node 2' },
      position: { x: 100, y: 100 },
    },
    {
      id: '3',
      data: { label: 'Node 3' },
      position: { x: 400, y: 100 },
    },
  ]);

  const edges = writable([
    { id: 'e1-2', source: '1', target: '2' },
    { id: 'e1-3', source: '1', target: '3' },
    { id: 'e3-4', source: '3', target: '4' },
    { id: 'e3-4b', source: '3', target: '4b', zIndex: 100 },
    { id: 'e4a-4b1', source: '4a', target: '4b1' },
    { id: 'e4a-4b2', source: '4a', target: '4b2', zIndex: 100 },
    { id: 'e4b1-4b2', source: '4b1', target: '4b2' },
  ]);
</script>

<main>
  <SvelteFlow {nodes} {edges} {nodeTypes} fitView minZoom={0.1} maxZoom={2.5}>
    <Controls />
    <Background variant={BackgroundVariant.Dots} />
    <MiniMap />
  </SvelteFlow>
</main>

<style>
  main {
    height: 100vh;
  }

  :global(.svelte-flow .svelte-flow__node.parent) {
    background-color: rgba(220, 220, 255, 0.4);
  }
</style>

// sites/reactflow.dev/src/components/example-viewer/example-flows/SubFlows/index.jsx
import { useCallback } from 'react';
import ReactFlow, {
  addEdge,
  Background,
  useNodesState,
  useEdgesState,
  MiniMap,
  Controls,
} from 'reactflow';
import 'reactflow/dist/style.css';

const initialNodes = [
  {
    id: '1',
    type: 'input',
    data: { label: 'Node 0' },
    position: { x: 250, y: 5 },
    className: 'light',
  },
  {
    id: '2',
    data: { label: 'Group A' },
    position: { x: 100, y: 100 },
    className: 'light',
    style: { backgroundColor: 'rgba(255, 0, 0, 0.2)', width: 200, height: 200 },
  },
  {
    id: '2a',
    data: { label: 'Node A.1' },
    position: { x: 10, y: 50 },
    parentId: '2',
  },
  {
    id: '3',
    data: { label: 'Node 1' },
    position: { x: 320, y: 100 },
    className: 'light',
  },
  {
    id: '4',
    data: { label: 'Group B' },
    position: { x: 320, y: 200 },
    className: 'light',
    style: { backgroundColor: 'rgba(255, 0, 0, 0.2)', width: 300, height: 300 },
    type: 'group',
  },
  {
    id: '4a',
    data: { label: 'Node B.1' },
    position: { x: 15, y: 65 },
    className: 'light',
    parentId: '4',
    extent: 'parent',
  },
  {
    id: '4b',
    data: { label: 'Group B.A' },
    position: { x: 15, y: 120 },
    className: 'light',
    style: {
      backgroundColor: 'rgba(255, 0, 255, 0.2)',
      height: 150,
      width: 270,
    },
    parentId: '4',
  },
  {
    id: '4b1',
    data: { label: 'Node B.A.1' },
    position: { x: 20, y: 40 },
    className: 'light',
    parentId: '4b',
  },
  {
    id: '4b2',
    data: { label: 'Node B.A.2' },
    position: { x: 100, y: 100 },
    className: 'light',
    parentId: '4b',
  },
];

const initialEdges = [
  { id: 'e1-2', source: '1', target: '2', animated: true },
  { id: 'e1-3', source: '1', target: '3' },
  { id: 'e2a-4a', source: '2a', target: '4a' },
  { id: 'e3-4b', source: '3', target: '4b' },
  { id: 'e4a-4b1', source: '4a', target: '4b1' },
  { id: 'e4a-4b2', source: '4a', target: '4b2' },
  { id: 'e4b1-4b2', source: '4b1', target: '4b2' },
];

const NestedFlow = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  const onConnect = useCallback((connection) => {
    setEdges((eds) => addEdge(connection, eds));
  }, []);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onConnect={onConnect}
      className="react-flow-subflows-example"
      fitView
    >
      <MiniMap />
      <Controls />
      <Background />
    </ReactFlow>
  );
};

export default NestedFlow;
