// apps/example-apps/svelte/examples/nodes/node-resizer/ResizableNode.svelte
<script lang="ts">
  import {
    Handle,
    NodeResizer,
    Position,
    type NodeProps,
  } from '@xyflow/svelte';

  let { data }: NodeProps = $props();
</script>

<NodeResizer minWidth={100} minHeight={30} />
<Handle type="target" position={Position.Left} />
<div style="padding: 10px">{data.label}</div>
<Handle type="source" position={Position.Right} />

// sites/reactflow.dev/src/components/example-viewer/example-flows/NodeResizer/ResizableNode.jsx
import { memo } from 'react';
import { Handle, Position, NodeResizer } from '@xyflow/react';

const ResizableNode = ({ data }) => {
  return (
    <>
      <NodeResizer minWidth={100} minHeight={30} />
      <Handle type="target" position={Position.Left} />
      <div style={{ padding: 10 }}>{data.label}</div>
      <Handle type="source" position={Position.Right} />
    </>
  );
};

export default memo(ResizableNode);
