// apps/example-apps/react/learn/basic-terms/NodeWrapper.jsx
const NodeWrapper = ({ children, bottom, top, left, right, width, height }) => {
  const toPx = (value) => (value !== undefined ? `${value}px` : undefined);

  return (
    <div
      className="react-flow__node-annotation"
      style={{
        position: 'absolute',
        fontSize: '12px',
        bottom: toPx(bottom),
        left: toPx(left),
        width: toPx(width),
        height: toPx(height),
        top: toPx(top),
        right: toPx(right),
      }}
    >
      {children}
    </div>
  );
};

export default NodeWrapper;

// apps/example-apps/svelte/guides/concepts/NodeWrapper.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  let {
    children,
    bottom,
    top,
    left,
    right,
    width,
    height,
  }: {
    children?: Snippet;
    bottom?: number;
    top?: number;
    left?: number;
    right?: number;
    width?: number;
    height?: number;
  } = $props();

  const toPx = (value: number | undefined) => (value ? `${value}px` : value);
</script>

<div
  class="svelte-flow__node-annotation"
  style:position="absolute"
  style:font-size="12px"
  style:bottom={toPx(bottom)}
  style:left={toPx(left)}
  style:width={toPx(width)}
  style:height={toPx(height)}
  style:top={toPx(top)}
  style:right={toPx(right)}
>
  {@render children?.()}
</div>
