// apps/example-apps/react/examples/misc/overview/TextNode.jsx
import React, { Fragment, memo } from 'react';
import { Handle, useStore, Position, useReactFlow } from '@xyflow/react';

const dimensionAttrs = ['width', 'height'];

export default memo(({ id }) => {
  const { setNodes } = useReactFlow();
  const dimensions = useStore((s) => {
    const node = s.nodeLookup.get('2-3');
    if (
      !node ||
      !node.measured.width ||
      !node.measured.height ||
      !s.edges.some((edge) => edge.target === id)
    ) {
      return null;
    }
    return {
      width: node.measured.width,
      height: node.measured.height,
    };
  });
  const updateDimension = (attr) => (event) => {
    setNodes((nds) =>
      nds.map((n) => {
        if (n.id === '2-3') {
          return {
            ...n,
            style: {
              ...n.style,
              [attr]: parseInt(event.target.value),
            },
          };
        }

        return n;
      }),
    );
  };
  
  return (
    <>
      {dimensionAttrs.map((attr) => (
        <Fragment key={attr}>
          <label>node {attr}</label>
          <input
            type="number"
            value={dimensions ? parseInt(dimensions[attr]) : 0}
            onChange={updateDimension(attr)}
            className="nodrag"
            disabled={!dimensions}
          />
        </Fragment>
      ))}
      {!dimensionAttrs && 'no node connected'}
      <Handle type="target" position={Position.Top} />
    </>
  );
});

// apps/example-apps/svelte/guides/concepts/TextNode.svelte
<script lang="ts">
  import {
    type NodeProps,
    Handle,
    Position,
    useNodeConnections,
    useInternalNode,
    type BuiltInNode,
    type Dimensions,
    useNodes,
  } from '@xyflow/svelte';

  let {}: NodeProps<BuiltInNode> = $props();

  const nodes = useNodes();

  const handleConnections = useNodeConnections({
    handleType: 'target',
  });

  let connectedNode = useInternalNode(handleConnections.current[0]?.source);
  let dimensions: null | Dimensions = $derived.by(() => {
    if (connectedNode.current?.measured.width && connectedNode.current.measured.height) {
      return {
        width: connectedNode.current.measured.width,
        height: connectedNode.current.measured.height,
      };
    }
    return null;
  });

  const updateDimension = (attr: string) => (event) => {
    nodes.update((nds) =>
      nds.map((n) => {
        if (n.id === '2-3') {
          return {
            ...n,
            [attr]: parseInt(event.target.value),
          };
        }

        return n;
      }),
    );
  };
</script>

{#each ['width', 'height'] as attr}
  <label>node {attr}</label>
  <input
    type="number"
    value={dimensions ? parseInt(dimensions[attr]) : 0}
    onchange={updateDimension(attr)}
    class="text-input-node__input nodrag"
    disabled={!dimensions}
  />
{/each}

{#if dimensions === null}
  no node connected
{/if}
<Handle type="target" position={Position.Top} class="custom-handle" />
