// apps/svelte-examples/src/routes/examples/nodes/drag-handle/DragHandleNode.svelte
<script lang="ts">
  import { Handle, Position, type NodeProps } from '@xyflow/svelte';

  type $$Props = NodeProps;
</script>

<Handle type="target" position={Position.Left} on:connect on:connectend on:connectstart />
<div class="label">
  Only draggable here →
  <!-- Use the class specified at node.dragHandle here -->
  <span class="drag-handle custom-drag-handle" />
</div>
<Handle type="source" position={Position.Right} on:connect on:connectend on:connectstart />

<style>
  .label {
    display: flex;
    align-items: center;
  }

  .drag-handle {
    display: inline-block;
    width: 25px;
    height: 25px;
    background-color: teal;
    margin-left: 5px;
    border-radius: 50%;
  }
</style>

// sites/reactflow.dev/src/components/example-viewer/example-flows/DragHandle/DragHandleNode.jsx
import React, { memo } from 'react';
import { Handle, Position } from '@xyflow/react';

const labelStyle = {
  display: 'flex',
  alignItems: 'center',
};

const dragHandleStyle = {
  display: 'inline-block',
  width: 25,
  height: 25,
  backgroundColor: 'teal',
  marginLeft: 5,
  borderRadius: '50%',
};

const onConnect = (params) => console.log('handle onConnect', params);

function DragHandleNode() {
  return (
    <>
      <Handle type="target" position={Position.Left} onConnect={onConnect} />
      <div style={labelStyle}>
        Only draggable here →
        {/* Use the class specified at node.dragHandle here */}
        <span className="custom-drag-handle" style={dragHandleStyle} />
      </div>
      <Handle type="source" position={Position.Right} />
    </>
  );
}

export default memo(DragHandleNode);
