// packages/xy-shared/widgets/hero-flow/color-picker-node.tsx
import { memo } from 'react';
import { NodeProps, Position, useReactFlow } from '@xyflow/react';
import { Text } from '@xyflow/xy-ui';

import Handle from './handle';
import Wrapper from './node-wrapper';

export default memo(({ data, id }: NodeProps) => {
  const { updateNodeData } = useReactFlow();

  return (
    <Wrapper label={data.label}>
      <div className="flex items-center space-x-2">
        <input
          className="nodrag border-md w-6 h-6"
          type="color"
          onChange={(evt) => updateNodeData(id, { value: evt.target.value })}
          defaultValue={data.value}
        />
        <Text size="xs" variant="light">
          {data.value}
        </Text>
      </div>
      <Handle type="source" position={Position.Right} />
    </Wrapper>
  );
});

// apps/example-apps/svelte/guides/custom-nodes/b/ColorPickerNode.svelte
<script lang="ts">
  import type { Writable } from 'svelte/store';
  import { Handle, Position, type Node, type NodeProps } from '@xyflow/svelte';

  let { data }: NodeProps<Node<{ color: Writable<string> }>> = $props();

  const { color } = data;
</script>

<div class="color-picker">
  <Handle type="target" position={Position.Left} />
  <div>
    mix color: <strong>{$color}</strong>
  </div>
  <input
    class="nodrag"
    type="color"
    on:input={(evt) => data.color.set(evt.target?.value)}
    value={$color}
  />
  <Handle type="source" position={Position.Right} />
</div>

<style>
  .color-picker {
    padding: 1rem;
    background: #eee;
    border-radius: 0.125rem;
    font-size: 0.7rem;
  }
</style>
