// apps/example-apps/svelte/examples/misc/download-image/CustomNode.svelte
<script lang="ts">
  import { Handle, Position, type NodeProps } from '@xyflow/svelte';

  let { isConnectable }: NodeProps = $props();
</script>

<Handle type="target" position={Position.Left} {isConnectable} />

<div>▼</div>
<Handle
  type="source"
  position={Position.Right}
  id="a"
  style="top:5px"
  {isConnectable}
/>
<Handle
  type="source"
  position={Position.Right}
  id="b"
  style="bottom:5px; top:auto"
  {isConnectable}
/>

// apps/example-apps/react/examples/edges/simple-floating-edges/CustomNode.jsx
import React, { memo } from 'react';
import { Handle, Position } from '@xyflow/react';

export default memo(({ data }) => {
  return (
    <>
      {data.label}
      <Handle type="source" position={Position.Top} id="a" />
      <Handle type="source" position={Position.Right} id="b" />
      <Handle type="source" position={Position.Bottom} id="c" />
      <Handle type="source" position={Position.Left} id="d" />
    </>
  );
});
