// apps/example-apps/svelte/examples/whiteboard/eraser/ErasableEdge.svelte
<script module>
  export type ErasableEdgeType = Edge<
    {
      toBeDeleted?: boolean;
    },
    'erasable-edge'
  >;
</script>

<script lang="ts">
  import {
    BaseEdge,
    type Edge,
    type EdgeProps,
    getSmoothStepPath,
    useInternalNode,
  } from '@xyflow/svelte';

  let {
    id,
    source,
    sourceX,
    sourceY,
    target,
    targetX,
    targetY,
    data,
  }: EdgeProps<ErasableEdgeType> = $props();

  const [edgePath] = $derived(getSmoothStepPath({ sourceX, sourceY, targetX, targetY }));

  const sourceNode = $derived(useInternalNode(source));
  const targetNode = $derived(useInternalNode(target));

  const toBeDeleted = $derived(
    data?.toBeDeleted ||
      sourceNode.current?.data.toBeDeleted ||
      targetNode.current?.data.toBeDeleted,
  );
</script>

<BaseEdge {id} path={edgePath} style="opacity: {toBeDeleted ? 0.3 : 1}" />

// apps/example-apps/react/examples/whiteboard/eraser/ErasableEdge.tsx
import {
  BaseEdge,
  type EdgeProps,
  type Edge,
  getSmoothStepPath,
  useInternalNode,
} from '@xyflow/react';
import { ErasableNodeType } from './ErasableNode';

export type ErasableEdgeType = Edge<{ toBeDeleted?: boolean }, 'erasable-edge'>;

export function ErasableEdge({
  id,
  source,
  sourceX,
  sourceY,
  target,
  targetX,
  targetY,
  data,
}: EdgeProps<ErasableEdgeType>) {
  const [edgePath] = getSmoothStepPath({ sourceX, sourceY, targetX, targetY });

  const sourceNode = useInternalNode<ErasableNodeType>(source);
  const targetNode = useInternalNode<ErasableNodeType>(target);

  const toBeDeleted =
    data?.toBeDeleted || sourceNode?.data.toBeDeleted || targetNode?.data.toBeDeleted;

  return <BaseEdge id={id} path={edgePath} style={{ opacity: toBeDeleted ? 0.3 : 1 }} />;
}
