// apps/svelte-examples/src/routes/examples/edges/custom-edges/BiDirectionalNode.svelte
<script lang="ts">
  import { Handle, Position, type NodeProps } from '@xyflow/svelte';

  type $$Props = NodeProps;

  export let data: $$Props['data'];
</script>

<div class="node">
  <Handle type="source" position={Position.Left} id="left" />
  {data?.label}
  <Handle type="source" position={Position.Right} id="right" />
</div>

<style>
  .node {
    padding: 10px;
    background: #fff;
    border: 1px solid #ddd;
  }
</style>

// sites/reactflow.dev/src/components/example-viewer/example-flows/CustomEdge/BiDirectionalNode.tsx
import React, { memo } from 'react';
import { Handle, NodeProps, Position } from '@xyflow/react';

const style = {
  padding: 10,
  background: '#fff',
  border: '1px solid #ddd',
};

const BiDirectionalNode = ({ data }: NodeProps) => {
  return (
    <div style={style}>
      <Handle type="source" position={Position.Left} id="left" />
      {data?.label}
      <Handle type="source" position={Position.Right} id="right" />
    </div>
  );
};

export default memo(BiDirectionalNode);
