// apps/example-apps/react/examples/nodes/custom-node/ColorSelectorNode.jsx
import React, { memo } from 'react';
import { Handle, Position } from '@xyflow/react';

export default memo(({ data, isConnectable }) => {
  return (
    <>
      <Handle
        type="target"
        position={Position.Left}
        onConnect={(params) => console.log('handle onConnect', params)}
        isConnectable={isConnectable}
      />
      <div>
        Custom Color Picker Node: <strong>{data.color}</strong>
      </div>
      <input
        className="nodrag"
        type="color"
        onChange={data.onChange}
        defaultValue={data.color}
      />
      <Handle
        type="source"
        position={Position.Right}
        isConnectable={isConnectable}
      />
    </>
  );
});

// apps/example-apps/svelte/examples/nodes/custom-node/ColorSelectorNode.svelte
<script lang="ts">
  import { Handle, Position, type NodeProps } from '@xyflow/svelte';
  import { bgColor } from './App.svelte';

  let { isConnectable }: NodeProps = $props();
</script>

<Handle type="target" position={Position.Left} {isConnectable} />
<div>
  Custom Color Picker Node: <strong>{bgColor.current}</strong>
</div>
<input class="nodrag" type="color" bind:value={bgColor.current} />
<Handle type="source" position={Position.Right} {isConnectable} />
