// apps/example-apps/react/learn/custom-node-2/TextUpdaterNode.jsx
import { Handle, Position } from '@xyflow/react';

const handleStyle = { left: 10 };

function TextUpdaterNode(props) {
  return (
    <div className="text-updater-node">
      <div>Custom Node</div>
      <Handle type="target" position={Position.Top} />
      <Handle type="source" position={Position.Bottom} id="a" style={handleStyle} />
      <Handle type="source" position={Position.Bottom} id="b" />
    </div>
  );
}

export default TextUpdaterNode;

// apps/example-apps/svelte/learn/custom-node-2/TextUpdaterNode.svelte
<script lang="ts">
  import { Handle, Position } from '@xyflow/svelte';
</script>

<div class="text-updater-node">
  <div>Custom Node</div>
  <Handle type="target" position={Position.Top} />
  <Handle type="source" position={Position.Bottom} id="a" style="left: 10px" />
  <Handle type="source" position={Position.Bottom} id="b" />
</div>

<style>
  .text-updater-node {
    height: 50px;
    border: var(--xy-node-border-default);
    padding: 5px;
    border-radius: 5px;
    background: var(--xy-node-background-color-default);
    color: var(--xy-node-color-default);
  }

  .text-updater-node label {
    display: block;
    font-size: 12px;
  }
</style>
