// apps/example-apps/svelte/examples/edges/custom-edges/BiDirectionalNode.svelte
<script lang="ts">
  import { Handle, Position, type NodeProps } from '@xyflow/svelte';

  let { data }: NodeProps = $props();
</script>

<div class="node">
  <Handle type="source" position={Position.Left} id="left" />
  {data?.label}
  <Handle type="source" position={Position.Right} id="right" />
</div>

<style>
  .node {
    padding: 10px;
    background: #fff;
    border: 1px solid #ddd;
  }
</style>

// apps/example-apps/react/examples/edges/custom-edges/BiDirectionalNode.tsx
import React, { memo } from 'react';
import { BuiltInNode, Handle, NodeProps, Position } from '@xyflow/react';

const style = {
  padding: 10,
  background: '#fff',
  border: '1px solid #ddd',
};

const BiDirectionalNode = ({ data }: NodeProps<BuiltInNode>) => {
  return (
    <div style={style}>
      <Handle type="source" position={Position.Left} id="left" />
      {data?.label}
      <Handle type="source" position={Position.Right} id="right" />
    </div>
  );
};

export default memo(BiDirectionalNode);
