// apps/svelte-examples/src/routes/examples/misc/feature-overview/AnnotationNode.svelte
<script lang="ts">
  import { type NodeProps } from '@xyflow/svelte';
  import type { AnnotationNode } from './types';

  type $$Props = NodeProps<AnnotationNode>;
  $$restProps;

  export let data: $$Props['data'];
</script>

<div style="padding: 10px; display: flex">
  <div style="marginRight: 4px">{data.level}.</div>
  <div>{data.label}</div>
</div>
{#if data.arrowStyle}
  <div class="arrow" style={data.arrowStyle}>⤹</div>
{/if}

// apps/example-apps/react/examples/misc/overview/AnnotationNode.jsx
import { memo } from 'react';

function AnnotationNode({ data }) {
  return (
    <>
      <div style={{ padding: 10, display: 'flex' }}>
        <div style={{ marginRight: 4 }}>{data.level}.</div>
        <div>{data.label}</div>
      </div>
      {data.arrowStyle && (
        <div className="arrow" style={data.arrowStyle}>
          ⤹
        </div>
      )}
    </>
  );
}

export default memo(AnnotationNode);
