// apps/example-apps/svelte/examples/misc/feature-overview/CircleNode.svelte
<script module>
  export type CircleNode = Node<{}>;
</script>

<script lang="ts">
  import { type NodeProps, Handle, type Node, Position } from '@xyflow/svelte';

  let { positionAbsoluteX, positionAbsoluteY }: NodeProps = $props();

  let label = $derived(
    `Position x:${Math.round(positionAbsoluteX)} y:${Math.round(positionAbsoluteY)}`,
  );
</script>

<div>{label || 'no node connected'}</div>
<Handle type="target" position={Position.Left} class="custom-handle" />

// apps/example-apps/react/examples/misc/overview/CircleNode.jsx
import React, { memo } from 'react';
import { Handle, Position } from '@xyflow/react';

export default memo(({ id, positionAbsoluteX, positionAbsoluteY }) => {
  const label = `Position x:${Math.round(positionAbsoluteX)} y:${Math.round(positionAbsoluteY)}`;

  return (
    <div>
      <div>{label || 'no node connected'}</div>
      <Handle
        type="target"
        position={Position.Left}
        className="custom-handle"
      />
    </div>
  );
});
